// Integration test: verifies that rustcore resolves the real gocore settings files
// (tests/fixtures/gocore/{settings.conf,settings_local.conf}) identically to Go.
//
// Expected values below were generated by running github.com/ordishs/gocore directly:
//
//   cd /tmp/gocore_probe/gocore_files
//   env -u SETTINGS_CONTEXT -u SETTINGS_APPLICATION \
//       -u name -u city -u number -u embedded -u varcity \
//       -u embedded2 -u secret -u multi -u single -u tel \
//       -u address -u app -u setting \
//       go run /tmp/gocore_probe/main.go 2>/dev/null
//
// Output (context "dev", no SETTINGS_APPLICATION):
//   name=Simon
//   city=Paris
//   number=5042
//   embedded=Simon lives in Paris
//   varcity=The big Paris
//   embedded2=Simon lives in The big Paris
//   secret=secret
//   multi=simon, peter, paul
//   single=zero
//   tel=20289202982
//   address=1 The Main Street
//   app=app

#[test]
fn gocore_settings_parity() {
    // Remove any env vars that might bleed in from the host environment and
    // shadow the fixture file values.
    let fixture_keys = [
        "SETTINGS_CONTEXT",
        "SETTINGS_APPLICATION",
        "name",
        "city",
        "number",
        "embedded",
        "varcity",
        "embedded2",
        "secret",
        "multi",
        "single",
        "tel",
        "address",
        "app",
        "setting",
    ];
    for k in &fixture_keys {
        unsafe {
            std::env::remove_var(k);
        }
    }

    // Explicit context = "dev" (Go default when SETTINGS_CONTEXT is unset).
    unsafe {
        std::env::set_var("SETTINGS_CONTEXT", "dev");
    }

    // chdir into the fixture directory so rustcore's discovery walks up from here
    // and finds exactly these two files (no stray settings.conf above /tmp).
    std::env::set_current_dir(
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/gocore"),
    )
    .unwrap();

    let c = rustcore::config::config();
    assert_eq!(c.context(), "dev");

    // Values verified against gocore output (see file header).
    assert_eq!(c.get("name").as_deref(), Some("Simon"));
    assert_eq!(c.get("city").as_deref(), Some("Paris"));
    assert_eq!(c.get("number").as_deref(), Some("5042"));
    assert_eq!(c.get("embedded").as_deref(), Some("Simon lives in Paris"));
    assert_eq!(c.get("varcity").as_deref(), Some("The big Paris"));
    assert_eq!(
        c.get("embedded2").as_deref(),
        Some("Simon lives in The big Paris")
    );
    // secret: Go's Get() strips *EHE* prefix after decryption
    assert_eq!(c.get("secret").as_deref(), Some("secret"));
    assert_eq!(c.get("multi").as_deref(), Some("simon, peter, paul"));
    assert_eq!(c.get("single").as_deref(), Some("zero"));
    assert_eq!(c.get("tel").as_deref(), Some("20289202982"));
    assert_eq!(c.get("address").as_deref(), Some("1 The Main Street"));
    assert_eq!(c.get("app").as_deref(), Some("app"));
}
